id: 006614d4-5626-4779-893f-0d06f4420a9e
title: FPS++ - 60fps
subtitle: Includes 60fps and DynamicFPS
description:
version: 1.0.0
category: 1
game:
  titleId: 0100F2C0115B6000
  version:
    - 1.1.2
    - 1.1.1
    - 1.1.0
    - 1.0.0
emulator:
  - 1
compatibility:
  blacklist:
    - 94201fd9-8f4d-4bb3-b87f-94ffc2b6e66d
author:
  - { name: somerandompeople, link: https://gbatemp.net/members/somerandompeople.648549/ }

